CREATE TABLE IF NOT EXISTS character_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_id BIGINT NOT NULL REFERENCES actions(id),
  character_id BIGINT NOT NULL REFERENCES characters(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  touched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (action_id, character_id)
);
