DO $$
BEGIN
  CREATE TYPE fight_reason AS ENUM ('gold', 'rank');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS fights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attacker BIGINT NOT NULL REFERENCES fighters(id),
  defender BIGINT REFERENCES fighters(id),
  victory BOOLEAN DEFAULT NULL,
  reason fight_reason NOT NULL,
  rank TEXT,
  details JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE TRIGGER fights_updated_at
  BEFORE UPDATE ON fights
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
